server:
  port: 9000

spring:
  application:
    name: core-gateway
  threads:
    virtual:
      enabled: true # Activa los Virtual Threads (Project Loom) en Java 21
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: analyzer_stream_route
          uri: http://analyzer-service.sentinelops-core.svc.cluster.local:80
          predicates:
            - Path=/api/stream/**
        - id: telemetry_route
          uri: http://telemetry-service.sentinelops-core.svc.cluster.local:80
          predicates:
            - Path=/api/telemetry/**
          filters:
            - name: CircuitBreaker
              args:
                name: defaultCircuitBreaker
                fallbackUri: forward:/fallback

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
